---
title: "tm-rule-rep-CM016"
output: html_document
date: "2024-06-12"
---
# Rule Code: CM016 

# Rule Title: ACH Spikes - Outgoing  

# Rule Logic:
Identify accounts with an upwards spike in Outgoing ACH activity that exceeds 68.50% and $10,000.00, between the last completed calendar month (month analyzed) and the average of the last 3 months (including analyzed).

```{r}
# Start-up ----
library(tidyverse)
library(magrittr)
library(skimr)
library(readxl)
```

```{r, warning=FALSE}
# Get Data ---- 
transaction_data = readRDS("C:/Users/E103986/.../.../data-work/data/prepd_abrigo-transaction-data.rds") %>% janitor::clean_names() # will need transaction amount from this data 

# mini corrections 
transaction_data = transaction_data %>%
  filter(transaction_type == "ACH") %>%
  filter(credit_debit == "Debit") %>%
  mutate(created_date = as.Date(created_date),
         tran_date = as.Date(tran_date))
## add transaction aggregation amount in the excel sheets # casewhen for thresholds and TIN code in cust
transaction_data = transaction_data %>%
  filter

#customer data
customer_data = read.csv("C:/Users/E103986/.../.../data-work/data/Customer Search Report.csv") %>% janitor::clean_names()

#mini corrections
customer_data = customer_data %>%
  mutate(acct = as.character(acct))

```


```{r}
# Read and Prep Historic Alerts ----
# read data
historic_alerts = readxl::read_excel("C:/Users/E103986/.../.../data-work/data/Alerts Report.xlsx", 
col_types = "text") %>% janitor::clean_names()

historic_alerts = historic_alerts %>%
  mutate(created_date = as.Date(as.numeric(created_date), origin = "1899-12-30"))

# filter for historic alerts
historic_alerts = historic_alerts %>% filter(origin_detail == "ACH Spikes - Outgoing")
historic_alerts = historic_alerts %>% filter(created_date >= "2023-03-01" & created_date <="2023-03-31")


```


```{r}
# Data Processing ---- 

# making a merged table w relevant fields
merged_data = transaction_data %>% 
  left_join(customer_data, by = c("acct_number" = "acct"))

#setting thresholds for business, indiv, and other 
business_thrhld = 100000
personal_thrld = 10000
other_thrhld = 10000

# Assigning threshold based on TIN code
merged_data = merged_data %>%
  mutate(thresholds = case_when(
    primary_tax_code == "F" ~ business_thrhld,
    primary_tax_code == "S" ~ personal_thrld,
    primary_tin == "N" ~ other_thrhld,
    TRUE ~ NA_real_
  ))

# deining the review period
review_period_start = as.Date("2023-03-01")
review_period_end = as.Date("2023-03-31")

#calculate last completed calendar month and avg 3 months

last_month = as.Date("2023-03-01")

three_month = last_month - months(3)

# filtering for trans completed previous months and the previous 3 months
last_month_data = merged_data %>%
  filter(tran_date >= last_month & tran_date < (last_month + months(1)))

three_month_data = merged_data %>%
  filter(tran_date >= three_month & tran_date < last_month)

#calculate total tran amount for last month
last_month_total = last_month_data %>%
  group_by(acct_number) %>%
  summarise(last_month_amount = sum(tran_amount, na.rm = TRUE))

# calculate the average tran amount for the 3 months
three_month_total = three_month_data %>%
  group_by(acct_number) %>%
  summarise(total_three_month_amt = sum(tran_amount, na.rm = TRUE)) %>%
  mutate(avg_three_month_total = total_three_month_amt / 3)

# divide by 3 to find the mean/average for 3 months and then filter for when spike is true 68.5%
#sum/average of the 3 months, filter for spike 68.5% 

# combining two dataframes
last_month_and_three_month = last_month_total %>%
  left_join(three_month_total, by = "acct_number")


```


```{r}
#rule logic

# average of the last 3 months spike of 68.5%
# Identify accounts with a spike in activity
rsm_alerts = last_month_and_three_month %>%
  filter(last_month_amount > avg_three_month_total * 1.685 & last_month_amount > 10000)

```

```{r}
rsm_alerts$.in_model = rsm_alerts$acct_number %in% historic_alerts$account_number
rsm_alerts$.review_comment = "N/A" # pre-populate
historic_alerts$.replicated = historic_alerts$account_number %in% rsm_alerts$acct_number
historic_alerts$.review_comment = "N/A" # pre-populate

replication_summary = tribble(~measure, ~value,
                              "RSM ALERTS", length(unique(rsm_alerts$acct_number)),
                              "MODEL ALERTS", length(unique(historic_alerts$account_number)),
                              "PCNT RSM ALERTS IN HISTORIC",
                              {length(unique(intersect(rsm_alerts$acct_number, historic_alerts$account_number)))/
                                  length(unique(rsm_alerts$acct_number))} %>% round(.,2),
                              "PCNT HISTORIC IN RSM ALERTS",
                              {length(unique(intersect(historic_alerts$account_number, rsm_alerts$acct_number)))/
                                  length(unique(historic_alerts$account_number))} %>% round(.,2)
)
replication_summary
```

```{r}
writexl::write_xlsx(
  x = list(
    "Summary" = replication_summary,
    "RSM Alerts" = rsm_alerts,
    "RSM Alerts UNQ" = dplyr::filter(rsm_alerts, !.in_model),
    "RSM Alerts UNQ TXNS" = merged_data %>% 
      filter(acct_number %in% filter(rsm_alerts, !.in_model)$acct_number),
    "MDL Alerts" = historic_alerts,
    "MDL Alerts UNQ" = filter(historic_alerts, !.replicated)
  ),
  path = ("C:/Users/E103986/.../.../data-work/logic-testing/output/CM016-rule-rep-analysis.xlsx")
)
```
