source("renv/activate.R")
set.seed(114783) # !!! UPDATE TO YOUR SPECIFIC PROJECT PIA # !!!
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(magrittr))
"%nin%" = Negate("%in%")

fs::file_create(path = here::here(".Renviron"))
fs::dir_create(here::here("./data"), recurse = TRUE)
fs::dir_create(here::here("./data/raw"), recurse = TRUE)
fs::dir_create(here::here("./data/prepd"), recurse = TRUE)
fs::dir_create(here::here("./data/external"), recurse = TRUE)
fs::dir_create(here::here("./data/temp"), recurse = TRUE)
fs::dir_create(here::here("./analysis/recon-cust-accnt/output"), recurse = TRUE)
fs::dir_create(here::here("./analysis/dq-cust-accnt/output"), recurse = TRUE)
fs::dir_create(here::here("./analysis/recon-txn/output"), recurse = TRUE)
fs::dir_create(here::here("./analysis/dq-txn/output"), recurse = TRUE)
fs::dir_create(here::here("./analysis/logic-testing/output"), recurse = TRUE)
fs::dir_create(here::here("./analysis/ref-lists/output"), recurse = TRUE)
fs::dir_create(here::here("./analysis/configs/output"), recurse = TRUE)
fs::dir_create(here::here("./analysis/other/output"), recurse = TRUE)
fs::dir_create(here::here("./analysis/misc/output"), recurse = TRUE)
fs::dir_create(here::here("./reports/output"), recurse = TRUE)
